### ISSUE TITLE
Port is ignored

### ISSUE THREAD

**Issue by phpPhil** [CircleOfNice/DoctrineRestDriver#53]
#### What is this feature about (expected vs actual behaviour)?
Expected: When specifying a port for the Doctrine connection the driver will request the REST service on the given port
Actual: The REST service is requested on the default HTTP port and I receive a message:

> Invalid url given: 127.0.0.1/myentity/1?

#### How can I reproduce it?
Specify a custom port (e.g. 8000) in Symfony 3 config.yml:
```
# Doctrine Configuration
doctrine:
    dbal:
        default_connection: restservices
        connections:
            restservices:
                driver_class: "Circle\\DoctrineRestDriver\\Driver"
                host: 127.0.0.1
                port: 8000
```
Then use the REST entity manager to fetch a record:
```
class MyController extends Controller
{
    /**
     * @Route("/")
     *
     */
    public function indexAction()
    {
        $singleresult = $this->getDoctrine()->getRepository('MyBundle:MyEntity')->find(1);
    }
}
```

#### Does it take minutes, hours or days to fix?
Unsure, but it doesn't sound too hard.
